[수정] delete duplicate for node styling
Terraform-Canvas/front-end pull request #39
Opened 2023-07-17 20:17 UTC by FacerAin

## Description
- css 상속을 활용한 중복되거나 사용되지 않는 노드 css 스타일링 제거

## Related Issue
close #26

2023-07-18 10:48 UTC, Eeap requested changes

2023-07-18 10:48 UTC, Eeap commented on src/components/node/NodePlane.vue
> +    </div>
요기 부분도 dialog를 alert로 바꿨더니 충돌 있는 것 같아

2023-07-18 10:48 UTC, Eeap commented on src/components/node/NodePlane.vue
> +    showModal.value = true;
이전 pr에서 수정된 부분 때문에 conflict가 있는 것 같아

2023-07-19 10:55 UTC, FacerAin commented on src/components/node/NodePlane.vue
> +    </div>
이전 버전들 기록 확인해서 충돌 해결해서 다시 PR 요청드려볼게요!

2023-07-26 05:25 UTC, FacerAin commented
conflict 해결해서 다시 리뷰 요청드릴게요:)

2023-07-26 06:12 UTC, Eeap approved these changes

2023-07-26 06:35 UTC, merged