[수정] node 상태 관리 변경 및 rightdrawer 확인 추가
Terraform-Canvas/front-end pull request #57
Opened 2023-08-01 06:33 UTC by FacerAin

## Description
- save 버튼 추가
- node 관리를 위한 전역 상태 관리 (vuex) 도입
- 전역적인 상태 관리 flow 수정 및 개선 예정 (작성 중, https://www.figma.com/file/gJb91DLnfaabDhe5zy5a4G/Terraform-Canvas?type=whiteboard&node-id=0%3A1&t=MAsOo7CUizV5jNGn-1)
![image](https://github.com/Terraform-Canvas/front-end/assets/16442978/f85cbc54-5b0d-44ae-a664-e4ec368ac7e8)

## Related Issue

2023-08-01 06:34 UTC, FacerAin commented
현재 동일 node 반복해서 수정시 text field가 정상 동작하지 않는 문제가 있어 해결해서 리뷰 요청 드릴게요 :)

2023-08-01 06:48 UTC, Eeap commented
> 현재 동일 node 반복해서 수정시 text field가 정상 동작하지 않는 문제가 있어 해결해서 리뷰 요청 드릴게요 :)

어떤 문제야?? 그리고 ec2 같은 경우 지금 sdk로 호출해서 combobox로 되어있을텐데

2023-08-01 06:50 UTC, Eeap requested changes

2023-08-01 06:50 UTC, Eeap commented on src/components/aws/DrawerInput.vue
> +            <v-col class="text-right">
v-row없이 v-col만 하면 적용되지 않을텐데?!

2023-08-01 06:50 UTC, Eeap commented on src/components/aws/DrawerInput.vue
> +            </v-col>
이 부분도..!

2023-08-01 06:50 UTC, Eeap commented on src/components/aws/DrawerInput.vue
> +            </v-col>
오잉 아래 더 체크했는데 반영 안됐네

2023-08-01 06:55 UTC, FacerAin commented on src/components/aws/DrawerInput.vue
> +            <v-col class="text-right">
앗 버튼을 오른쪽으로 두고 싶어서 쓴 구문인데,
잘 옮겨지길래 신경을 못썼네요 :(

말씀하신 것처럼 맥락상 v-row가 맞는 것 같아요!
좋은 지적 감사합니당 :)

2023-08-01 07:10 UTC, FacerAin commented
> > 현재 동일 node 반복해서 수정시 text field가 정상 동작하지 않는 문제가 있어 해결해서 리뷰 요청 드릴게요 :)
> 
> 어떤 문제야?? 그리고 ec2 같은 경우 지금 sdk로 호출해서 combobox로 되어있을텐데

node 내부에 입력하는 값들이나  store에 들어가는 값들은 잘 반영이 되는데,
**어떤 한 node의 drawer를 중복해서 여러번 열었을  때**, 변경된 값들이 v-text-field에 실시간으로 잘 반영되지 않는다는 문제가 있어요! 제 생각에는 store에서 노드 데이터 받아오는 시점과 화면에 렌더링하는 시점 사이에 뭔가 문제가 있는 것 같아서 요부분 살펴보고 있어요!

ec2 콤보박스 관련해서는  테스트 용으로 백엔드 서버 껐는데, v-combobox 자체적으로 **내부에 :items가 비어있으면 자동으로 v-text-field로 동작**해서 그런 것 같아요. 실제 production 환경에서는 문제 없어요! :)

2023-08-01 08:39 UTC, Eeap approved these changes

2023-08-02 06:55 UTC, FacerAin commented
@Eeap 
**문제 상황**: Drawer를 Save 버튼이 아닌 **Drawer 바깥을 클릭하여 닫았을 때 Drawer 내 form들의 value가 잘 초기화되지 않는 문제**가 있습니다. 따라서 사용자가 save 버튼을 누르지 않았는데 drawer를 닫았다가 다시 열면 해당 값들이 그대로 남아있는 문제가 있습니다. (실제 node data에는 반영 안됨.)
watch나 onUpdated와  같은 훅 등을 drawer가 닫히는 시점을 이용하여 해결하려고 하였으나 잘 해결이 되지 않아서 공유를 드립니다

생각하고 있는 해결방안은 아래와 같습니다.
**방안 1:**
   **drawer 바깥쪽을 클릭했을 때 닫히는 event를 막아버리고**, 저장이나 취소 버튼을 이용해서만 drawer를 닫을 수 있게 하기
👍 pros: 구현도 간단하고, 개발자가 다뤄야 할 이벤트 케이스들이 단순해짐 
👎 cons: 사용자 관점에서 drawer 외부를 눌러도 닫히지 않아 UI가 부자연스러울 수 있음

![image](https://github.com/Terraform-Canvas/front-end/assets/16442978/2b79d535-d1cd-4e6e-9025-3ee349eafbe1)

 **방안 2:**
**drawer 바깥쪽을 클릭했을 때 닫히는 event는 그대로 두고**, 컴포넌트 리팩토링이나 추가적인 기법등을 통해 해결방안 찾아보기
👍 pros: 사용자가 기대하는 drawer UI 상호작용 구현 가능
👎 cons: 개발 소요 발생

어떤 방안으로 나아가면 좋을지 소중한 의견 부탁드려요 :)

2023-08-02 10:02 UTC, Eeap commented
1방안으로 다른버튼을 통해서 닫는건 막고 보통 창 닫는 x 표시 버튼과 취소 버튼을 같이 넣어서 유저 입장에서 버튼을 닫아야 닫히는구나라고 생각하눈게 어떨까

2023-08-03 11:56 UTC, FacerAin commented
@Eeap  말씀하신 것처럼 아래 그림처럼 **1) 외부 입력 이벤트 막기 2) X 표시 버튼 추가 3) 취소 버튼 추가** 완료했습니다 :)
![image](https://github.com/Terraform-Canvas/front-end/assets/16442978/3ae0c30d-f49f-4cdd-97a6-a4b00065d3fb)

2023-08-03 15:22 UTC, Eeap commented
> @Eeap 말씀하신 것처럼 아래 그림처럼 **1) 외부 입력 이벤트 막기 2) X 표시 버튼 추가 3) 취소 버튼 추가** 완료했습니다 :) ![image](https://user-images.githubusercontent.com/16442978/258103716-3ae0c30d-f49f-4cdd-97a6-a4b00065d3fb.png)

음.. save를 오른쪽으로 하면 좋을 것 같구 NAT Gateway처럼 입력할 value가 없는 경우 save 같은게 필요할까라는 생각이 드네..

2023-08-04 02:11 UTC, FacerAin commented
> > @Eeap 말씀하신 것처럼 아래 그림처럼 **1) 외부 입력 이벤트 막기 2) X 표시 버튼 추가 3) 취소 버튼 추가** 완료했습니다 :) ![image](https://user-images.githubusercontent.com/16442978/258103716-3ae0c30d-f49f-4cdd-97a6-a4b00065d3fb.png)
> 
> 음.. save를 오른쪽으로 하면 좋을 것 같구 NAT Gateway처럼 입력할 value가 없는 경우 save 같은게 필요할까라는 생각이 드네..

save랑 cancel 위치 변경했구, 입력할 value가 없는 경우 UI 수정은 #65 여기 이슈와 함께 처리할게요!

2023-08-05 06:55 UTC, merged